export const archetypes: any = {
  "E-girl": [
    "Lulu",
    "Nami",
    "Janna",
    "Yuumi",
    "Soraka",
    "Sona",
    "Lux",
    "Karma",
  ],
  Healer: [],
  Shielder: ["Janna", "Lulu", "Karma"],
  "Tank Player": [
    "Ornn",
    "Shen",
    "Malphite",
    "Sejuani",
    "Rammus",
    "Maokai",
    "Chogath",
    "Udyr",
    "Zac",
    "Volibear",
    "Amumu",
    "DrMundo",
  ],
  Tryhard: [
    "Vayne",
    "Katarina",
    "Yasuo",
    "Yone",
    "Irelia",
    "Azir",
    "Riven",
    "Lee Sin",
    "Fiora",
    "Fizz",
    "Aphelios",
    "Kalista",
    "Ryze",
    "Qiyana",
    "Jayce",
    "Sylas",
    "Cassiopeia",
    "Draven",
    "Viego",
    "Kayle",
    "Rengar",
    "Zed",
    "Samira",
    "Master Yi",
    "Kassadin",
  ],
  "Invisibility Abuser": ["Evelynn", "Twitch", "Khazix", "Akshan"],
  "Lifesteal Abuser": [
    "Aatrox",
    "Kayn",
    "Vladimir",
    "Darius",
    "Kled",
    "Olaf",
    "Warwick",
    "Swain",
  ],
};
